version: '3.8'

services:


  web: # service name
    build: .
    env_file:
      - .env
    command: bash -c "python manage.py migrate ; python manage.py collectstatic --noinput ; python manage.py runserver 0.0.0.0:8000"

    restart: "always"
    depends_on:
      - db

  db:
    image: postgres:11-alpine

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
      - POSTGRES_USER=${POSTGRES_USER}

    restart: "on-failure"

volumes:
  postgres_data: